version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env.docker
    # Connect to external MongoDB and Redis
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - MONGODB_URI=mongodb://host.docker.internal:27017/saka-kazi
      - REDIS_URL=redis://host.docker.internal:6379

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
